[package]
name = "fw16-pong-wars"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.2"
anyhow = "1.0"
rand = "0.8"
tray-icon = "0.11"

[profile.release]
opt-level = 3
lto = true
strip = true

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
